-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.aggregate_program_stats (
  stat_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  program_id uuid NOT NULL,
  stat_date date NOT NULL,
  stat_type character varying NOT NULL,
  total_observations integer,
  total_sites integer,
  active_petris integer,
  active_gasifiers integer,
  avg_growth_index numeric,
  growth_trend numeric,
  growth_acceleration numeric,
  overall_effectiveness_score numeric,
  best_performing_site_id uuid,
  worst_performing_site_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT aggregate_program_stats_pkey PRIMARY KEY (stat_id),
  CONSTRAINT aggregate_program_stats_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT aggregate_program_stats_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id)
);
CREATE TABLE public.async_error_logs (
  log_id bigint NOT NULL DEFAULT nextval('async_error_logs_log_id_seq'::regclass),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  table_name text NOT NULL,
  trigger_name text NOT NULL,
  function_name text NOT NULL,
  payload jsonb DEFAULT '{}'::jsonb,
  http_method text,
  endpoint text,
  status text NOT NULL DEFAULT 'error'::text,
  error_message text,
  error_details jsonb,
  request_id bigint,
  retry_count integer NOT NULL DEFAULT 0,
  next_retry_at timestamp with time zone,
  completed_at timestamp with time zone,
  CONSTRAINT async_error_logs_pkey PRIMARY KEY (log_id)
);
CREATE TABLE public.companies (
  company_id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  website character varying,
  logo_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  default_weather USER-DEFINED DEFAULT 'Clear'::weather_enum,
  CONSTRAINT companies_pkey PRIMARY KEY (company_id)
);
CREATE TABLE public.custom_reports_legacy (
  report_id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  created_by_user_id uuid NOT NULL,
  company_id uuid NOT NULL,
  program_id uuid,
  configuration jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT custom_reports_legacy_pkey PRIMARY KEY (report_id),
  CONSTRAINT custom_reports_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES auth.users(id),
  CONSTRAINT custom_reports_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT custom_reports_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id)
);
CREATE TABLE public.dashboard_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  dashboard_id uuid NOT NULL,
  user_id uuid,
  session_id character varying,
  event_type character varying NOT NULL,
  event_data jsonb DEFAULT '{}'::jsonb,
  widget_id uuid,
  viewport_width integer,
  viewport_height integer,
  device_type character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dashboard_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT dashboard_analytics_dashboard_id_fkey FOREIGN KEY (dashboard_id) REFERENCES public.dashboards(id),
  CONSTRAINT dashboard_analytics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT dashboard_analytics_widget_id_fkey FOREIGN KEY (widget_id) REFERENCES public.dashboard_widgets(id)
);
CREATE TABLE public.dashboard_comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  dashboard_id uuid NOT NULL,
  widget_id uuid,
  parent_comment_id uuid,
  content text NOT NULL,
  position_x integer,
  position_y integer,
  is_resolved boolean DEFAULT false,
  resolved_by uuid,
  resolved_at timestamp with time zone,
  author_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dashboard_comments_pkey PRIMARY KEY (id),
  CONSTRAINT dashboard_comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id),
  CONSTRAINT dashboard_comments_dashboard_id_fkey FOREIGN KEY (dashboard_id) REFERENCES public.dashboards(id),
  CONSTRAINT dashboard_comments_widget_id_fkey FOREIGN KEY (widget_id) REFERENCES public.dashboard_widgets(id),
  CONSTRAINT dashboard_comments_parent_comment_id_fkey FOREIGN KEY (parent_comment_id) REFERENCES public.dashboard_comments(id),
  CONSTRAINT dashboard_comments_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.users(id)
);
CREATE TABLE public.dashboard_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  dashboard_id uuid NOT NULL,
  user_id uuid NOT NULL,
  permission_level character varying NOT NULL CHECK (permission_level::text = ANY (ARRAY['viewer'::character varying, 'editor'::character varying, 'admin'::character varying]::text[])),
  can_edit boolean DEFAULT false,
  can_delete boolean DEFAULT false,
  can_share boolean DEFAULT false,
  can_export boolean DEFAULT false,
  can_comment boolean DEFAULT true,
  granted_by uuid NOT NULL,
  granted_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dashboard_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT dashboard_permissions_dashboard_id_fkey FOREIGN KEY (dashboard_id) REFERENCES public.dashboards(id),
  CONSTRAINT dashboard_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT dashboard_permissions_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES public.users(id)
);
CREATE TABLE public.dashboard_shares (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  dashboard_id uuid NOT NULL,
  share_type character varying NOT NULL CHECK (share_type::text = ANY (ARRAY['view'::character varying, 'edit'::character varying, 'embed'::character varying]::text[])),
  access_level character varying NOT NULL CHECK (access_level::text = ANY (ARRAY['public'::character varying, 'company'::character varying, 'users'::character varying, 'password'::character varying]::text[])),
  password_hash text,
  expires_at timestamp with time zone,
  allowed_users ARRAY,
  embed_config jsonb DEFAULT '{"theme": "light", "showHeader": true, "showFilters": true, "allowInteraction": true}'::jsonb,
  share_token character varying NOT NULL DEFAULT encode(gen_random_bytes(32), 'hex'::text) UNIQUE,
  view_count integer DEFAULT 0,
  last_viewed_at timestamp with time zone,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dashboard_shares_pkey PRIMARY KEY (id),
  CONSTRAINT dashboard_shares_dashboard_id_fkey FOREIGN KEY (dashboard_id) REFERENCES public.dashboards(id),
  CONSTRAINT dashboard_shares_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.dashboard_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  category character varying,
  layout_config jsonb NOT NULL,
  widgets_config jsonb NOT NULL,
  preview_image_url text,
  tags ARRAY DEFAULT ARRAY[]::text[],
  usage_count integer DEFAULT 0,
  rating numeric DEFAULT 0,
  created_by uuid NOT NULL,
  company_id uuid,
  is_public boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dashboard_templates_pkey PRIMARY KEY (id),
  CONSTRAINT dashboard_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT dashboard_templates_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id)
);
CREATE TABLE public.dashboard_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  dashboard_id uuid NOT NULL,
  version_number integer NOT NULL,
  name character varying,
  description text,
  dashboard_config jsonb NOT NULL,
  widgets_config jsonb NOT NULL,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT false,
  size_bytes integer,
  checksum character varying,
  CONSTRAINT dashboard_versions_pkey PRIMARY KEY (id),
  CONSTRAINT dashboard_versions_dashboard_id_fkey FOREIGN KEY (dashboard_id) REFERENCES public.dashboards(id),
  CONSTRAINT dashboard_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.dashboard_widgets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  dashboard_id uuid NOT NULL,
  widget_type character varying NOT NULL CHECK (widget_type::text = ANY (ARRAY['report'::character varying, 'text'::character varying, 'image'::character varying, 'metric'::character varying, 'iframe'::character varying, 'custom'::character varying]::text[])),
  report_id uuid,
  position_x integer NOT NULL DEFAULT 0,
  position_y integer NOT NULL DEFAULT 0,
  width integer NOT NULL DEFAULT 4,
  height integer NOT NULL DEFAULT 3,
  title character varying,
  show_title boolean DEFAULT true,
  show_border boolean DEFAULT true,
  background_color character varying,
  border_color character varying,
  border_radius integer DEFAULT 8,
  has_shadow boolean DEFAULT true,
  z_index integer DEFAULT 0,
  is_visible boolean DEFAULT true,
  is_resizable boolean DEFAULT true,
  is_movable boolean DEFAULT true,
  configuration jsonb DEFAULT '{}'::jsonb,
  responsive_config jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dashboard_widgets_pkey PRIMARY KEY (id),
  CONSTRAINT dashboard_widgets_dashboard_id_fkey FOREIGN KEY (dashboard_id) REFERENCES public.dashboards(id),
  CONSTRAINT dashboard_widgets_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.saved_reports(report_id)
);
CREATE TABLE public.dashboards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  layout_type character varying DEFAULT 'grid'::character varying CHECK (layout_type::text = ANY (ARRAY['grid'::character varying, 'free'::character varying, 'tabs'::character varying, 'stack'::character varying]::text[])),
  layout_config jsonb DEFAULT '{"gap": 16, "rows": 8, "columns": 12, "padding": 16}'::jsonb,
  created_by uuid NOT NULL,
  company_id uuid NOT NULL,
  is_public boolean DEFAULT false,
  refresh_frequency integer DEFAULT 0,
  auto_refresh boolean DEFAULT false,
  theme_config jsonb DEFAULT '{}'::jsonb,
  tags ARRAY DEFAULT ARRAY[]::text[],
  view_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dashboards_pkey PRIMARY KEY (id),
  CONSTRAINT dashboards_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT dashboards_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id)
);
CREATE TABLE public.effectiveness_metrics (
  metric_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  program_id uuid NOT NULL,
  site_id uuid NOT NULL,
  calculation_date date NOT NULL,
  phase_name character varying,
  growth_suppression_rate numeric,
  coverage_effectiveness numeric,
  treatment_efficiency numeric,
  treatment_cost_usd numeric,
  pest_damage_prevented_usd numeric,
  roi_percentage numeric,
  payback_period_days integer,
  vs_control_improvement numeric,
  vs_industry_benchmark numeric,
  vs_previous_phase numeric,
  avg_temperature numeric,
  avg_humidity numeric,
  weather_impact_score numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT effectiveness_metrics_pkey PRIMARY KEY (metric_id),
  CONSTRAINT effectiveness_metrics_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT effectiveness_metrics_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT effectiveness_metrics_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id)
);
CREATE TABLE public.gasifier_obs_part_default (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  gasifier_code text NOT NULL,
  image_url text,
  chemical_type USER-DEFINED NOT NULL DEFAULT 'Citronella Blend'::chemical_type_enum,
  measure numeric,
  anomaly boolean NOT NULL DEFAULT false,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  lastupdated_by uuid,
  program_id uuid NOT NULL,
  placement_height USER-DEFINED,
  directional_placement USER-DEFINED,
  placement_strategy USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  order_index integer,
  position_x numeric,
  position_y numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT '0'::numeric,
  linear_reading real,
  linear_reduction_nominal real DEFAULT '6'::real,
  linear_reduction_per_day real DEFAULT '6'::real,
  flow_rate real DEFAULT '6'::real,
  flag_for_review boolean DEFAULT false,
  daysinthisprogramphase numeric DEFAULT 0,
  todays_day_of_phase numeric DEFAULT 0,
  yesterday_reading numeric DEFAULT '6'::numeric,
  company_id uuid NOT NULL,
  forecasted_expiration timestamp without time zone,
  trend_gasifier_velocity USER-DEFINED,
  CONSTRAINT gasifier_obs_part_default_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT gasifier_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT gasifier_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT gasifier_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id)
);
CREATE TABLE public.gasifier_obs_prog_191ce66ce8a1494eb4670ccd3e9708bf (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  gasifier_code text NOT NULL,
  image_url text,
  chemical_type USER-DEFINED NOT NULL DEFAULT 'Citronella Blend'::chemical_type_enum,
  measure numeric,
  anomaly boolean NOT NULL DEFAULT false,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  lastupdated_by uuid,
  program_id uuid NOT NULL,
  placement_height USER-DEFINED,
  directional_placement USER-DEFINED,
  placement_strategy USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  order_index integer,
  position_x numeric,
  position_y numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT '0'::numeric,
  linear_reading real,
  linear_reduction_nominal real DEFAULT '6'::real,
  linear_reduction_per_day real DEFAULT '6'::real,
  flow_rate real DEFAULT '6'::real,
  flag_for_review boolean DEFAULT false,
  daysinthisprogramphase numeric DEFAULT 0,
  todays_day_of_phase numeric DEFAULT 0,
  yesterday_reading numeric DEFAULT '6'::numeric,
  company_id uuid NOT NULL,
  forecasted_expiration timestamp without time zone,
  trend_gasifier_velocity USER-DEFINED,
  CONSTRAINT gasifier_obs_prog_191ce66ce8a1494eb4670ccd3e9708bf_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT gasifier_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT gasifier_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT gasifier_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id)
);
CREATE TABLE public.gasifier_obs_prog_3808a3bd6d7a4ffb9a3bccb580d2d5f8 (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  gasifier_code text NOT NULL,
  image_url text,
  chemical_type USER-DEFINED NOT NULL DEFAULT 'Citronella Blend'::chemical_type_enum,
  measure numeric,
  anomaly boolean NOT NULL DEFAULT false,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  lastupdated_by uuid,
  program_id uuid NOT NULL,
  placement_height USER-DEFINED,
  directional_placement USER-DEFINED,
  placement_strategy USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  order_index integer,
  position_x numeric,
  position_y numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT '0'::numeric,
  linear_reading real,
  linear_reduction_nominal real DEFAULT '6'::real,
  linear_reduction_per_day real DEFAULT '6'::real,
  flow_rate real DEFAULT '6'::real,
  flag_for_review boolean DEFAULT false,
  daysinthisprogramphase numeric DEFAULT 0,
  todays_day_of_phase numeric DEFAULT 0,
  yesterday_reading numeric DEFAULT '6'::numeric,
  company_id uuid NOT NULL,
  forecasted_expiration timestamp without time zone,
  trend_gasifier_velocity USER-DEFINED,
  CONSTRAINT gasifier_obs_prog_3808a3bd6d7a4ffb9a3bccb580d2d5f8_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT gasifier_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT gasifier_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT gasifier_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id)
);
CREATE TABLE public.gasifier_obs_prog_3ed8dc59274441f9b751038ea2385063 (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  gasifier_code text NOT NULL,
  image_url text,
  chemical_type USER-DEFINED NOT NULL DEFAULT 'Citronella Blend'::chemical_type_enum,
  measure numeric,
  anomaly boolean NOT NULL DEFAULT false,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  lastupdated_by uuid,
  program_id uuid NOT NULL,
  placement_height USER-DEFINED,
  directional_placement USER-DEFINED,
  placement_strategy USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  order_index integer,
  position_x numeric,
  position_y numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT '0'::numeric,
  linear_reading real,
  linear_reduction_nominal real DEFAULT '6'::real,
  linear_reduction_per_day real DEFAULT '6'::real,
  flow_rate real DEFAULT '6'::real,
  flag_for_review boolean DEFAULT false,
  daysinthisprogramphase numeric DEFAULT 0,
  todays_day_of_phase numeric DEFAULT 0,
  yesterday_reading numeric DEFAULT '6'::numeric,
  company_id uuid NOT NULL,
  forecasted_expiration timestamp without time zone,
  trend_gasifier_velocity USER-DEFINED,
  CONSTRAINT gasifier_obs_prog_3ed8dc59274441f9b751038ea2385063_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT gasifier_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT gasifier_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT gasifier_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id)
);
CREATE TABLE public.gasifier_obs_prog_711262dfcf5e47cdbb7cf5d92804fea9 (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  gasifier_code text NOT NULL,
  image_url text,
  chemical_type USER-DEFINED NOT NULL DEFAULT 'Citronella Blend'::chemical_type_enum,
  measure numeric,
  anomaly boolean NOT NULL DEFAULT false,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  lastupdated_by uuid,
  program_id uuid NOT NULL,
  placement_height USER-DEFINED,
  directional_placement USER-DEFINED,
  placement_strategy USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  order_index integer,
  position_x numeric,
  position_y numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT '0'::numeric,
  linear_reading real,
  linear_reduction_nominal real DEFAULT '6'::real,
  linear_reduction_per_day real DEFAULT '6'::real,
  flow_rate real DEFAULT '6'::real,
  flag_for_review boolean DEFAULT false,
  daysinthisprogramphase numeric DEFAULT 0,
  todays_day_of_phase numeric DEFAULT 0,
  yesterday_reading numeric DEFAULT '6'::numeric,
  company_id uuid NOT NULL,
  forecasted_expiration timestamp without time zone,
  trend_gasifier_velocity USER-DEFINED,
  CONSTRAINT gasifier_obs_prog_711262dfcf5e47cdbb7cf5d92804fea9_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT gasifier_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT gasifier_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT gasifier_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id)
);
CREATE TABLE public.gasifier_obs_prog_ea425513e594423b82767e8cd2bbd309 (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  gasifier_code text NOT NULL,
  image_url text,
  chemical_type USER-DEFINED NOT NULL DEFAULT 'Citronella Blend'::chemical_type_enum,
  measure numeric,
  anomaly boolean NOT NULL DEFAULT false,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  lastupdated_by uuid,
  program_id uuid NOT NULL,
  placement_height USER-DEFINED,
  directional_placement USER-DEFINED,
  placement_strategy USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  order_index integer,
  position_x numeric,
  position_y numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT '0'::numeric,
  linear_reading real,
  linear_reduction_nominal real DEFAULT '6'::real,
  linear_reduction_per_day real DEFAULT '6'::real,
  flow_rate real DEFAULT '6'::real,
  flag_for_review boolean DEFAULT false,
  daysinthisprogramphase numeric DEFAULT 0,
  todays_day_of_phase numeric DEFAULT 0,
  yesterday_reading numeric DEFAULT '6'::numeric,
  company_id uuid NOT NULL,
  forecasted_expiration timestamp without time zone,
  trend_gasifier_velocity USER-DEFINED,
  CONSTRAINT gasifier_obs_prog_ea425513e594423b82767e8cd2bbd309_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT gasifier_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT gasifier_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT gasifier_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id)
);
CREATE TABLE public.gasifier_observations (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  gasifier_code text NOT NULL,
  image_url text,
  chemical_type USER-DEFINED NOT NULL DEFAULT 'Citronella Blend'::chemical_type_enum,
  measure numeric CHECK (measure >= 0::numeric AND measure <= 10::numeric),
  anomaly boolean NOT NULL DEFAULT false,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  lastupdated_by uuid,
  program_id uuid,
  placement_height USER-DEFINED,
  directional_placement USER-DEFINED,
  placement_strategy USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  order_index integer,
  position_x numeric,
  position_y numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric CHECK (footage_from_origin_x >= 0::numeric),
  footage_from_origin_y numeric DEFAULT '0'::numeric CHECK (footage_from_origin_y >= 0::numeric),
  linear_reading real,
  linear_reduction_nominal real DEFAULT '6'::real CHECK (linear_reduction_nominal < 6.01::double precision),
  linear_reduction_per_day real DEFAULT '6'::real CHECK (linear_reduction_per_day < 6.1::double precision),
  flow_rate real DEFAULT '6'::real,
  flag_for_review boolean DEFAULT false,
  daysinthisprogramphase numeric DEFAULT 0,
  todays_day_of_phase numeric DEFAULT 0,
  yesterday_reading numeric DEFAULT '6'::numeric,
  company_id uuid NOT NULL,
  CONSTRAINT gasifier_observations_pkey PRIMARY KEY (observation_id),
  CONSTRAINT gasifier_observations_last_updated_by_user_id_fkey FOREIGN KEY (last_updated_by_user_id) REFERENCES auth.users(id),
  CONSTRAINT gasifier_observations_lastupdated_by_fkey FOREIGN KEY (lastupdated_by) REFERENCES auth.users(id),
  CONSTRAINT gasifier_observations_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT gasifier_observations_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT gasifier_observations_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id)
);
CREATE TABLE public.gasifier_observations_partitioned (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  gasifier_code text NOT NULL,
  image_url text,
  chemical_type USER-DEFINED NOT NULL DEFAULT 'Citronella Blend'::chemical_type_enum,
  measure numeric,
  anomaly boolean NOT NULL DEFAULT false,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  lastupdated_by uuid,
  program_id uuid NOT NULL,
  placement_height USER-DEFINED,
  directional_placement USER-DEFINED,
  placement_strategy USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  order_index integer,
  position_x numeric,
  position_y numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT '0'::numeric,
  linear_reading real,
  linear_reduction_nominal real DEFAULT '6'::real,
  linear_reduction_per_day real DEFAULT '6'::real,
  flow_rate real DEFAULT '6'::real,
  flag_for_review boolean DEFAULT false,
  daysinthisprogramphase numeric DEFAULT 0,
  todays_day_of_phase numeric DEFAULT 0,
  yesterday_reading numeric DEFAULT '6'::numeric,
  company_id uuid NOT NULL,
  forecasted_expiration timestamp without time zone,
  trend_gasifier_velocity USER-DEFINED,
  CONSTRAINT gasifier_observations_partitioned_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT gasifier_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT gasifier_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT gasifier_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id)
);
CREATE TABLE public.performance_benchmarks (
  benchmark_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid,
  benchmark_type character varying NOT NULL,
  metric_name character varying NOT NULL,
  metric_value numeric NOT NULL,
  unit character varying,
  conditions jsonb,
  valid_from date NOT NULL,
  valid_to date,
  source character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT performance_benchmarks_pkey PRIMARY KEY (benchmark_id),
  CONSTRAINT performance_benchmarks_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id)
);
CREATE TABLE public.petri_obs_default (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  petri_code character varying NOT NULL,
  image_url text,
  fungicide_used USER-DEFINED NOT NULL,
  surrounding_water_schedule USER-DEFINED NOT NULL,
  notes character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  program_name character varying,
  lastupdated_by uuid,
  plant_type USER-DEFINED DEFAULT 'Other Fresh Perishable'::plant_type_enum,
  program_id uuid NOT NULL,
  placement USER-DEFINED,
  placement_dynamics USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  petri_growth_stage USER-DEFINED DEFAULT 'None'::petri_growth_stage,
  growth_index numeric DEFAULT '0'::numeric,
  order_index integer,
  x_position numeric,
  y_position numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT 0,
  growth_progression numeric DEFAULT 0.00,
  growth_aggression numeric DEFAULT 0.00,
  growth_velocity real,
  todays_day_of_phase numeric DEFAULT '0'::numeric,
  is_image_split boolean DEFAULT false,
  phase_observation_settings jsonb,
  is_missed_observation boolean DEFAULT false,
  main_petri_id uuid,
  is_split_source boolean DEFAULT false,
  split_processed boolean DEFAULT false,
  flag_for_review boolean,
  company_id uuid NOT NULL,
  CONSTRAINT petri_obs_default_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT petri_observations_partitioned_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT petri_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT petri_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT petri_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id),
  CONSTRAINT petri_observations_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id)
);
CREATE TABLE public.petri_obs_part_default (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  petri_code character varying NOT NULL,
  image_url text,
  fungicide_used USER-DEFINED NOT NULL,
  surrounding_water_schedule USER-DEFINED NOT NULL,
  notes character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  program_name character varying,
  lastupdated_by uuid,
  plant_type USER-DEFINED DEFAULT 'Other Fresh Perishable'::plant_type_enum,
  program_id uuid NOT NULL,
  placement USER-DEFINED,
  placement_dynamics USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  petri_growth_stage USER-DEFINED DEFAULT 'None'::petri_growth_stage,
  growth_index numeric DEFAULT '0'::numeric,
  order_index integer,
  x_position numeric,
  y_position numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT 0,
  growth_progression numeric DEFAULT 0.00,
  growth_aggression numeric DEFAULT 0.00,
  growth_velocity real,
  todays_day_of_phase numeric DEFAULT '0'::numeric,
  is_image_split boolean DEFAULT false,
  phase_observation_settings jsonb,
  is_missed_observation boolean DEFAULT false,
  main_petri_id uuid,
  is_split_source boolean DEFAULT false,
  split_processed boolean DEFAULT false,
  flag_for_review boolean,
  company_id uuid NOT NULL,
  trend_petri_velocity USER-DEFINED,
  experiment_role USER-DEFINED,
  CONSTRAINT petri_obs_part_default_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT petri_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT petri_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT petri_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id)
);
CREATE TABLE public.petri_obs_prog_191ce66c_e8a1_494e_b467_0ccd3e9708bf (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  petri_code character varying NOT NULL,
  image_url text,
  fungicide_used USER-DEFINED NOT NULL,
  surrounding_water_schedule USER-DEFINED NOT NULL,
  notes character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  program_name character varying,
  lastupdated_by uuid,
  plant_type USER-DEFINED DEFAULT 'Other Fresh Perishable'::plant_type_enum,
  program_id uuid NOT NULL,
  placement USER-DEFINED,
  placement_dynamics USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  petri_growth_stage USER-DEFINED DEFAULT 'None'::petri_growth_stage,
  growth_index numeric DEFAULT '0'::numeric,
  order_index integer,
  x_position numeric,
  y_position numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT 0,
  growth_progression numeric DEFAULT 0.00,
  growth_aggression numeric DEFAULT 0.00,
  growth_velocity real,
  todays_day_of_phase numeric DEFAULT '0'::numeric,
  is_image_split boolean DEFAULT false,
  phase_observation_settings jsonb,
  is_missed_observation boolean DEFAULT false,
  main_petri_id uuid,
  is_split_source boolean DEFAULT false,
  split_processed boolean DEFAULT false,
  flag_for_review boolean,
  company_id uuid NOT NULL,
  CONSTRAINT petri_obs_prog_191ce66c_e8a1_494e_b467_0ccd3e9708bf_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT petri_observations_partitioned_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT petri_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT petri_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT petri_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id),
  CONSTRAINT petri_observations_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id)
);
CREATE TABLE public.petri_obs_prog_191ce66ce8a1494eb4670ccd3e9708bf (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  petri_code character varying NOT NULL,
  image_url text,
  fungicide_used USER-DEFINED NOT NULL,
  surrounding_water_schedule USER-DEFINED NOT NULL,
  notes character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  program_name character varying,
  lastupdated_by uuid,
  plant_type USER-DEFINED DEFAULT 'Other Fresh Perishable'::plant_type_enum,
  program_id uuid NOT NULL,
  placement USER-DEFINED,
  placement_dynamics USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  petri_growth_stage USER-DEFINED DEFAULT 'None'::petri_growth_stage,
  growth_index numeric DEFAULT '0'::numeric,
  order_index integer,
  x_position numeric,
  y_position numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT 0,
  growth_progression numeric DEFAULT 0.00,
  growth_aggression numeric DEFAULT 0.00,
  growth_velocity real,
  todays_day_of_phase numeric DEFAULT '0'::numeric,
  is_image_split boolean DEFAULT false,
  phase_observation_settings jsonb,
  is_missed_observation boolean DEFAULT false,
  main_petri_id uuid,
  is_split_source boolean DEFAULT false,
  split_processed boolean DEFAULT false,
  flag_for_review boolean,
  company_id uuid NOT NULL,
  trend_petri_velocity USER-DEFINED,
  experiment_role USER-DEFINED,
  CONSTRAINT petri_obs_prog_191ce66ce8a1494eb4670ccd3e9708bf_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT petri_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id),
  CONSTRAINT petri_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT petri_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id)
);
CREATE TABLE public.petri_obs_prog_3808a3bd6d7a4ffb9a3bccb580d2d5f8 (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  petri_code character varying NOT NULL,
  image_url text,
  fungicide_used USER-DEFINED NOT NULL,
  surrounding_water_schedule USER-DEFINED NOT NULL,
  notes character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  program_name character varying,
  lastupdated_by uuid,
  plant_type USER-DEFINED DEFAULT 'Other Fresh Perishable'::plant_type_enum,
  program_id uuid NOT NULL,
  placement USER-DEFINED,
  placement_dynamics USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  petri_growth_stage USER-DEFINED DEFAULT 'None'::petri_growth_stage,
  growth_index numeric DEFAULT '0'::numeric,
  order_index integer,
  x_position numeric,
  y_position numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT 0,
  growth_progression numeric DEFAULT 0.00,
  growth_aggression numeric DEFAULT 0.00,
  growth_velocity real,
  todays_day_of_phase numeric DEFAULT '0'::numeric,
  is_image_split boolean DEFAULT false,
  phase_observation_settings jsonb,
  is_missed_observation boolean DEFAULT false,
  main_petri_id uuid,
  is_split_source boolean DEFAULT false,
  split_processed boolean DEFAULT false,
  flag_for_review boolean,
  company_id uuid NOT NULL,
  trend_petri_velocity USER-DEFINED,
  experiment_role USER-DEFINED,
  CONSTRAINT petri_obs_prog_3808a3bd6d7a4ffb9a3bccb580d2d5f8_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT petri_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id),
  CONSTRAINT petri_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT petri_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id)
);
CREATE TABLE public.petri_obs_prog_3808a3bd_6d7a_4ffb_9a3b_ccb580d2d5f8 (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  petri_code character varying NOT NULL,
  image_url text,
  fungicide_used USER-DEFINED NOT NULL,
  surrounding_water_schedule USER-DEFINED NOT NULL,
  notes character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  program_name character varying,
  lastupdated_by uuid,
  plant_type USER-DEFINED DEFAULT 'Other Fresh Perishable'::plant_type_enum,
  program_id uuid NOT NULL,
  placement USER-DEFINED,
  placement_dynamics USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  petri_growth_stage USER-DEFINED DEFAULT 'None'::petri_growth_stage,
  growth_index numeric DEFAULT '0'::numeric,
  order_index integer,
  x_position numeric,
  y_position numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT 0,
  growth_progression numeric DEFAULT 0.00,
  growth_aggression numeric DEFAULT 0.00,
  growth_velocity real,
  todays_day_of_phase numeric DEFAULT '0'::numeric,
  is_image_split boolean DEFAULT false,
  phase_observation_settings jsonb,
  is_missed_observation boolean DEFAULT false,
  main_petri_id uuid,
  is_split_source boolean DEFAULT false,
  split_processed boolean DEFAULT false,
  flag_for_review boolean,
  company_id uuid NOT NULL,
  CONSTRAINT petri_obs_prog_3808a3bd_6d7a_4ffb_9a3b_ccb580d2d5f8_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT petri_observations_partitioned_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT petri_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT petri_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT petri_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id),
  CONSTRAINT petri_observations_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id)
);
CREATE TABLE public.petri_obs_prog_3ed8dc59274441f9b751038ea2385063 (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  petri_code character varying NOT NULL,
  image_url text,
  fungicide_used USER-DEFINED NOT NULL,
  surrounding_water_schedule USER-DEFINED NOT NULL,
  notes character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  program_name character varying,
  lastupdated_by uuid,
  plant_type USER-DEFINED DEFAULT 'Other Fresh Perishable'::plant_type_enum,
  program_id uuid NOT NULL,
  placement USER-DEFINED,
  placement_dynamics USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  petri_growth_stage USER-DEFINED DEFAULT 'None'::petri_growth_stage,
  growth_index numeric DEFAULT '0'::numeric,
  order_index integer,
  x_position numeric,
  y_position numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT 0,
  growth_progression numeric DEFAULT 0.00,
  growth_aggression numeric DEFAULT 0.00,
  growth_velocity real,
  todays_day_of_phase numeric DEFAULT '0'::numeric,
  is_image_split boolean DEFAULT false,
  phase_observation_settings jsonb,
  is_missed_observation boolean DEFAULT false,
  main_petri_id uuid,
  is_split_source boolean DEFAULT false,
  split_processed boolean DEFAULT false,
  flag_for_review boolean,
  company_id uuid NOT NULL,
  trend_petri_velocity USER-DEFINED,
  experiment_role USER-DEFINED,
  CONSTRAINT petri_obs_prog_3ed8dc59274441f9b751038ea2385063_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT petri_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id),
  CONSTRAINT petri_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT petri_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id)
);
CREATE TABLE public.petri_obs_prog_3ed8dc59_2744_41f9_b751_038ea2385063 (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  petri_code character varying NOT NULL,
  image_url text,
  fungicide_used USER-DEFINED NOT NULL,
  surrounding_water_schedule USER-DEFINED NOT NULL,
  notes character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  program_name character varying,
  lastupdated_by uuid,
  plant_type USER-DEFINED DEFAULT 'Other Fresh Perishable'::plant_type_enum,
  program_id uuid NOT NULL,
  placement USER-DEFINED,
  placement_dynamics USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  petri_growth_stage USER-DEFINED DEFAULT 'None'::petri_growth_stage,
  growth_index numeric DEFAULT '0'::numeric,
  order_index integer,
  x_position numeric,
  y_position numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT 0,
  growth_progression numeric DEFAULT 0.00,
  growth_aggression numeric DEFAULT 0.00,
  growth_velocity real,
  todays_day_of_phase numeric DEFAULT '0'::numeric,
  is_image_split boolean DEFAULT false,
  phase_observation_settings jsonb,
  is_missed_observation boolean DEFAULT false,
  main_petri_id uuid,
  is_split_source boolean DEFAULT false,
  split_processed boolean DEFAULT false,
  flag_for_review boolean,
  company_id uuid NOT NULL,
  CONSTRAINT petri_obs_prog_3ed8dc59_2744_41f9_b751_038ea2385063_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT petri_observations_partitioned_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT petri_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT petri_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT petri_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id),
  CONSTRAINT petri_observations_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id)
);
CREATE TABLE public.petri_obs_prog_711262df_cf5e_47cd_bb7c_f5d92804fea9 (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  petri_code character varying NOT NULL,
  image_url text,
  fungicide_used USER-DEFINED NOT NULL,
  surrounding_water_schedule USER-DEFINED NOT NULL,
  notes character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  program_name character varying,
  lastupdated_by uuid,
  plant_type USER-DEFINED DEFAULT 'Other Fresh Perishable'::plant_type_enum,
  program_id uuid NOT NULL,
  placement USER-DEFINED,
  placement_dynamics USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  petri_growth_stage USER-DEFINED DEFAULT 'None'::petri_growth_stage,
  growth_index numeric DEFAULT '0'::numeric,
  order_index integer,
  x_position numeric,
  y_position numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT 0,
  growth_progression numeric DEFAULT 0.00,
  growth_aggression numeric DEFAULT 0.00,
  growth_velocity real,
  todays_day_of_phase numeric DEFAULT '0'::numeric,
  is_image_split boolean DEFAULT false,
  phase_observation_settings jsonb,
  is_missed_observation boolean DEFAULT false,
  main_petri_id uuid,
  is_split_source boolean DEFAULT false,
  split_processed boolean DEFAULT false,
  flag_for_review boolean,
  company_id uuid NOT NULL,
  CONSTRAINT petri_obs_prog_711262df_cf5e_47cd_bb7c_f5d92804fea9_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT petri_observations_partitioned_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT petri_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT petri_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT petri_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id),
  CONSTRAINT petri_observations_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id)
);
CREATE TABLE public.petri_obs_prog_711262dfcf5e47cdbb7cf5d92804fea9 (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  petri_code character varying NOT NULL,
  image_url text,
  fungicide_used USER-DEFINED NOT NULL,
  surrounding_water_schedule USER-DEFINED NOT NULL,
  notes character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  program_name character varying,
  lastupdated_by uuid,
  plant_type USER-DEFINED DEFAULT 'Other Fresh Perishable'::plant_type_enum,
  program_id uuid NOT NULL,
  placement USER-DEFINED,
  placement_dynamics USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  petri_growth_stage USER-DEFINED DEFAULT 'None'::petri_growth_stage,
  growth_index numeric DEFAULT '0'::numeric,
  order_index integer,
  x_position numeric,
  y_position numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT 0,
  growth_progression numeric DEFAULT 0.00,
  growth_aggression numeric DEFAULT 0.00,
  growth_velocity real,
  todays_day_of_phase numeric DEFAULT '0'::numeric,
  is_image_split boolean DEFAULT false,
  phase_observation_settings jsonb,
  is_missed_observation boolean DEFAULT false,
  main_petri_id uuid,
  is_split_source boolean DEFAULT false,
  split_processed boolean DEFAULT false,
  flag_for_review boolean,
  company_id uuid NOT NULL,
  trend_petri_velocity USER-DEFINED,
  experiment_role USER-DEFINED,
  CONSTRAINT petri_obs_prog_711262dfcf5e47cdbb7cf5d92804fea9_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT petri_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id),
  CONSTRAINT petri_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT petri_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id)
);
CREATE TABLE public.petri_obs_prog_ea425513_e594_423b_8276_7e8cd2bbd309 (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  petri_code character varying NOT NULL,
  image_url text,
  fungicide_used USER-DEFINED NOT NULL,
  surrounding_water_schedule USER-DEFINED NOT NULL,
  notes character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  program_name character varying,
  lastupdated_by uuid,
  plant_type USER-DEFINED DEFAULT 'Other Fresh Perishable'::plant_type_enum,
  program_id uuid NOT NULL,
  placement USER-DEFINED,
  placement_dynamics USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  petri_growth_stage USER-DEFINED DEFAULT 'None'::petri_growth_stage,
  growth_index numeric DEFAULT '0'::numeric,
  order_index integer,
  x_position numeric,
  y_position numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT 0,
  growth_progression numeric DEFAULT 0.00,
  growth_aggression numeric DEFAULT 0.00,
  growth_velocity real,
  todays_day_of_phase numeric DEFAULT '0'::numeric,
  is_image_split boolean DEFAULT false,
  phase_observation_settings jsonb,
  is_missed_observation boolean DEFAULT false,
  main_petri_id uuid,
  is_split_source boolean DEFAULT false,
  split_processed boolean DEFAULT false,
  flag_for_review boolean,
  company_id uuid NOT NULL,
  CONSTRAINT petri_obs_prog_ea425513_e594_423b_8276_7e8cd2bbd309_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT petri_observations_partitioned_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT petri_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT petri_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT petri_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id),
  CONSTRAINT petri_observations_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id)
);
CREATE TABLE public.petri_obs_prog_ea425513e594423b82767e8cd2bbd309 (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  petri_code character varying NOT NULL,
  image_url text,
  fungicide_used USER-DEFINED NOT NULL,
  surrounding_water_schedule USER-DEFINED NOT NULL,
  notes character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  program_name character varying,
  lastupdated_by uuid,
  plant_type USER-DEFINED DEFAULT 'Other Fresh Perishable'::plant_type_enum,
  program_id uuid NOT NULL,
  placement USER-DEFINED,
  placement_dynamics USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  petri_growth_stage USER-DEFINED DEFAULT 'None'::petri_growth_stage,
  growth_index numeric DEFAULT '0'::numeric,
  order_index integer,
  x_position numeric,
  y_position numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT 0,
  growth_progression numeric DEFAULT 0.00,
  growth_aggression numeric DEFAULT 0.00,
  growth_velocity real,
  todays_day_of_phase numeric DEFAULT '0'::numeric,
  is_image_split boolean DEFAULT false,
  phase_observation_settings jsonb,
  is_missed_observation boolean DEFAULT false,
  main_petri_id uuid,
  is_split_source boolean DEFAULT false,
  split_processed boolean DEFAULT false,
  flag_for_review boolean,
  company_id uuid NOT NULL,
  trend_petri_velocity USER-DEFINED,
  experiment_role USER-DEFINED,
  CONSTRAINT petri_obs_prog_ea425513e594423b82767e8cd2bbd309_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT petri_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id),
  CONSTRAINT petri_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT petri_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id)
);
CREATE TABLE public.petri_observations (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  petri_code character varying NOT NULL,
  image_url text,
  fungicide_used USER-DEFINED NOT NULL,
  surrounding_water_schedule USER-DEFINED NOT NULL,
  notes character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  program_name character varying,
  lastupdated_by uuid,
  plant_type USER-DEFINED DEFAULT 'Other Fresh Perishable'::plant_type_enum,
  program_id uuid NOT NULL,
  placement USER-DEFINED,
  placement_dynamics USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  petri_growth_stage USER-DEFINED DEFAULT 'None'::petri_growth_stage,
  growth_index numeric DEFAULT '0'::numeric,
  order_index integer,
  x_position numeric,
  y_position numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT 0,
  growth_progression numeric DEFAULT 0.00,
  growth_aggression numeric DEFAULT 0.00,
  growth_velocity real,
  todays_day_of_phase numeric DEFAULT '0'::numeric,
  is_image_split boolean DEFAULT false,
  phase_observation_settings jsonb,
  is_missed_observation boolean DEFAULT false,
  main_petri_id uuid,
  is_split_source boolean DEFAULT false,
  split_processed boolean DEFAULT false,
  flag_for_review boolean,
  company_id uuid NOT NULL,
  CONSTRAINT petri_observations_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT petri_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT petri_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT petri_observations_partitioned_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT petri_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id),
  CONSTRAINT petri_observations_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id)
);
CREATE TABLE public.petri_observations_backup_growth (
  observation_id uuid,
  growth_progression numeric,
  growth_index numeric,
  petri_code character varying,
  program_id uuid,
  todays_day_of_phase numeric
);
CREATE TABLE public.petri_observations_original (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  petri_code character varying NOT NULL,
  image_url text,
  fungicide_used USER-DEFINED NOT NULL,
  surrounding_water_schedule USER-DEFINED NOT NULL,
  notes character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  program_name character varying,
  lastupdated_by uuid,
  plant_type USER-DEFINED DEFAULT 'Other Fresh Perishable'::plant_type_enum,
  program_id uuid,
  placement USER-DEFINED,
  placement_dynamics USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  petri_growth_stage USER-DEFINED DEFAULT 'None'::petri_growth_stage,
  growth_index numeric DEFAULT '0'::numeric CHECK (growth_index < 11::numeric),
  order_index integer,
  x_position numeric,
  y_position numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric CHECK (footage_from_origin_x >= 0::numeric),
  footage_from_origin_y numeric DEFAULT 0 CHECK (footage_from_origin_y >= 0::numeric),
  growth_progression numeric DEFAULT 0.00 CHECK (growth_progression >= 0::numeric),
  growth_aggression numeric DEFAULT 0.00 CHECK (growth_aggression >= '-1000'::integer::numeric),
  growth_velocity real,
  daysInThisProgramPhase numeric,
  todays_day_of_phase numeric DEFAULT '0'::numeric,
  is_image_split boolean DEFAULT false,
  phase_observation_settings jsonb,
  is_missed_observation boolean DEFAULT false,
  main_petri_id uuid,
  is_split_source boolean DEFAULT false,
  split_processed boolean DEFAULT false,
  flag_for_review boolean,
  company_id uuid NOT NULL,
  CONSTRAINT petri_observations_original_pkey PRIMARY KEY (observation_id),
  CONSTRAINT petri_observations_last_updated_by_user_id_fkey FOREIGN KEY (last_updated_by_user_id) REFERENCES auth.users(id),
  CONSTRAINT petri_observations_lastupdated_by_fkey FOREIGN KEY (lastupdated_by) REFERENCES auth.users(id),
  CONSTRAINT fk_petri_observations_program_id FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT petri_observations_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT petri_observations_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id)
);
CREATE TABLE public.petri_observations_partitioned (
  observation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  site_id uuid NOT NULL,
  petri_code character varying NOT NULL,
  image_url text,
  fungicide_used USER-DEFINED NOT NULL,
  surrounding_water_schedule USER-DEFINED NOT NULL,
  notes character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  program_name character varying,
  lastupdated_by uuid,
  plant_type USER-DEFINED DEFAULT 'Other Fresh Perishable'::plant_type_enum,
  program_id uuid NOT NULL,
  placement USER-DEFINED,
  placement_dynamics USER-DEFINED,
  last_updated_by_user_id uuid,
  last_edit_time timestamp with time zone DEFAULT now(),
  outdoor_temperature numeric,
  outdoor_humidity numeric,
  petri_growth_stage USER-DEFINED DEFAULT 'None'::petri_growth_stage,
  growth_index numeric DEFAULT '0'::numeric,
  order_index integer,
  x_position numeric,
  y_position numeric,
  footage_from_origin_x numeric DEFAULT '0'::numeric,
  footage_from_origin_y numeric DEFAULT 0,
  growth_progression numeric DEFAULT 0.00,
  growth_aggression numeric DEFAULT 0.00,
  growth_velocity real,
  todays_day_of_phase numeric DEFAULT '0'::numeric,
  is_image_split boolean DEFAULT false,
  phase_observation_settings jsonb,
  is_missed_observation boolean DEFAULT false,
  main_petri_id uuid,
  is_split_source boolean DEFAULT false,
  split_processed boolean DEFAULT false,
  flag_for_review boolean,
  company_id uuid NOT NULL,
  trend_petri_velocity USER-DEFINED,
  experiment_role USER-DEFINED,
  CONSTRAINT petri_observations_partitioned_pkey PRIMARY KEY (observation_id, program_id),
  CONSTRAINT petri_observations_partitioned_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id),
  CONSTRAINT petri_observations_partitioned_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT petri_observations_partitioned_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id)
);
CREATE TABLE public.pilot_program_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_timestamp timestamp with time zone NOT NULL DEFAULT now(),
  update_type USER-DEFINED NOT NULL,
  object_id uuid NOT NULL,
  object_type text NOT NULL,
  program_id uuid,
  user_id uuid,
  user_email text,
  user_company text,
  user_role text,
  old_data jsonb,
  new_data jsonb,
  ip_address text,
  user_agent text,
  CONSTRAINT pilot_program_history_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pilot_program_history_staging (
  id uuid NOT NULL,
  event_timestamp timestamp with time zone,
  update_type text,
  object_id uuid,
  object_type text,
  program_id uuid,
  user_id uuid,
  user_email text,
  user_company text,
  user_role text,
  old_data jsonb,
  new_data jsonb,
  ip_address text,
  user_agent text,
  CONSTRAINT pilot_program_history_staging_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pilot_program_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  program_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'Respond'::user_role_enum,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_email character varying,
  CONSTRAINT pilot_program_users_pkey PRIMARY KEY (id),
  CONSTRAINT pilot_program_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT pilot_program_users_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id)
);
CREATE TABLE public.pilot_programs (
  program_id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  status USER-DEFINED NOT NULL,
  total_submissions integer DEFAULT 0,
  total_sites integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  lastupdated_by uuid,
  company_id uuid,
  cloned_from_program_id uuid,
  phases jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT pilot_programs_pkey PRIMARY KEY (program_id),
  CONSTRAINT pilot_programs_lastupdated_by_fkey FOREIGN KEY (lastupdated_by) REFERENCES auth.users(id),
  CONSTRAINT pilot_programs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id)
);
CREATE TABLE public.report_access_logs (
  log_id bigint NOT NULL DEFAULT nextval('report_access_logs_log_id_seq'::regclass),
  report_id uuid NOT NULL,
  accessed_by uuid NOT NULL,
  accessed_at timestamp with time zone NOT NULL DEFAULT now(),
  access_type character varying NOT NULL,
  ip_address inet,
  user_agent text,
  load_time_ms integer,
  export_format character varying,
  CONSTRAINT report_access_logs_pkey PRIMARY KEY (log_id),
  CONSTRAINT report_access_logs_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.saved_reports(report_id),
  CONSTRAINT report_access_logs_accessed_by_fkey FOREIGN KEY (accessed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.report_data_snapshots (
  snapshot_id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL,
  version_number integer NOT NULL,
  snapshot_data jsonb NOT NULL,
  raw_data_sample jsonb,
  data_timestamp timestamp with time zone NOT NULL,
  snapshot_created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid NOT NULL,
  query_runtime_ms integer,
  data_row_count integer,
  data_size_bytes bigint,
  is_current boolean DEFAULT true,
  change_summary text,
  CONSTRAINT report_data_snapshots_pkey PRIMARY KEY (snapshot_id),
  CONSTRAINT report_data_snapshots_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.saved_reports(report_id),
  CONSTRAINT report_data_snapshots_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.report_folder_permissions (
  permission_id uuid NOT NULL DEFAULT gen_random_uuid(),
  folder_id uuid NOT NULL,
  user_id uuid NOT NULL,
  permission_level USER-DEFINED NOT NULL DEFAULT 'viewer'::folder_permission_level,
  granted_by uuid NOT NULL,
  granted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT report_folder_permissions_pkey PRIMARY KEY (permission_id),
  CONSTRAINT report_folder_permissions_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES public.report_folders(folder_id),
  CONSTRAINT report_folder_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT report_folder_permissions_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES auth.users(id)
);
CREATE TABLE public.report_folders (
  folder_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  parent_folder_id uuid,
  folder_name character varying NOT NULL CHECK (folder_name::text <> ''::text),
  folder_path text,
  description text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_archived boolean DEFAULT false,
  folder_order integer DEFAULT 0,
  icon character varying DEFAULT 'folder'::character varying,
  color character varying DEFAULT '#6B7280'::character varying,
  CONSTRAINT report_folders_pkey PRIMARY KEY (folder_id),
  CONSTRAINT report_folders_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT report_folders_parent_folder_id_fkey FOREIGN KEY (parent_folder_id) REFERENCES public.report_folders(folder_id),
  CONSTRAINT report_folders_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.report_subscriptions (
  subscription_id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL,
  subscriber_id uuid NOT NULL,
  frequency USER-DEFINED NOT NULL,
  send_day_of_week integer,
  send_day_of_month integer,
  send_time time without time zone DEFAULT '08:00:00'::time without time zone,
  timezone character varying DEFAULT 'UTC'::character varying,
  status USER-DEFINED DEFAULT 'active'::subscription_status,
  last_sent_at timestamp with time zone,
  next_send_at timestamp with time zone,
  email_format character varying DEFAULT 'pdf'::character varying,
  include_raw_data boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT report_subscriptions_pkey PRIMARY KEY (subscription_id),
  CONSTRAINT report_subscriptions_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.saved_reports(report_id),
  CONSTRAINT report_subscriptions_subscriber_id_fkey FOREIGN KEY (subscriber_id) REFERENCES auth.users(id)
);
CREATE TABLE public.report_version_history (
  history_id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL,
  version_number integer NOT NULL,
  change_type character varying NOT NULL,
  change_description text,
  previous_config jsonb,
  new_config jsonb,
  changed_by uuid NOT NULL,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  restored_from_version integer,
  CONSTRAINT report_version_history_pkey PRIMARY KEY (history_id),
  CONSTRAINT report_version_history_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.saved_reports(report_id),
  CONSTRAINT report_version_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.report_visualizations (
  visualization_id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL,
  visualization_type character varying NOT NULL,
  visualization_config jsonb NOT NULL,
  display_order integer DEFAULT 0,
  layout_config jsonb,
  title character varying,
  subtitle text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT report_visualizations_pkey PRIMARY KEY (visualization_id),
  CONSTRAINT report_visualizations_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.saved_reports(report_id)
);
CREATE TABLE public.saved_reports (
  report_id uuid NOT NULL DEFAULT gen_random_uuid(),
  folder_id uuid NOT NULL,
  company_id uuid NOT NULL,
  report_name character varying NOT NULL CHECK (report_name::text <> ''::text),
  description text,
  report_type character varying NOT NULL,
  report_config jsonb NOT NULL,
  data_source_config jsonb NOT NULL,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_accessed_at timestamp with time zone,
  access_count integer DEFAULT 0,
  is_draft boolean DEFAULT false,
  is_archived boolean DEFAULT false,
  is_template boolean DEFAULT false,
  estimated_runtime_ms integer,
  last_refresh_at timestamp with time zone,
  auto_refresh_enabled boolean DEFAULT false,
  refresh_interval_hours integer,
  CONSTRAINT saved_reports_pkey PRIMARY KEY (report_id),
  CONSTRAINT saved_reports_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES public.report_folders(folder_id),
  CONSTRAINT saved_reports_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id),
  CONSTRAINT saved_reports_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.site_snapshots (
  snapshot_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  program_id uuid NOT NULL,
  site_id uuid NOT NULL,
  site_code bigint NOT NULL,
  phase_descriptor character varying,
  snapshot_date date NOT NULL,
  placements_snapshot jsonb DEFAULT '{}'::jsonb,
  airflow_snapshot jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  day_number integer NOT NULL DEFAULT 1,
  snapshot_sequence integer DEFAULT 1,
  CONSTRAINT site_snapshots_pkey PRIMARY KEY (snapshot_id)
);
CREATE TABLE public.sites (
  site_id uuid NOT NULL DEFAULT gen_random_uuid(),
  program_id uuid NOT NULL,
  name character varying NOT NULL,
  type USER-DEFINED NOT NULL,
  total_petris integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  program_name character varying,
  lastupdated_by uuid,
  submission_defaults jsonb,
  petri_defaults jsonb DEFAULT '[]'::jsonb,
  default_temperature numeric,
  default_humidity numeric,
  default_weather USER-DEFINED,
  default_indoor_temperature numeric CHECK (default_indoor_temperature >= 32::numeric AND default_indoor_temperature <= 120::numeric),
  default_indoor_humidity numeric CHECK (default_indoor_humidity >= 1::numeric AND default_indoor_humidity <= 100::numeric),
  gasifier_defaults jsonb DEFAULT '[]'::jsonb,
  total_gasifiers integer DEFAULT 0,
  square_footage numeric CHECK (square_footage >= 100::numeric AND square_footage <= 1000000000::numeric),
  cubic_footage numeric CHECK (cubic_footage >= 25::numeric AND cubic_footage <= 1000000::numeric),
  num_vents integer CHECK (num_vents >= 1 AND num_vents <= 10000),
  vent_placements ARRAY,
  primary_function USER-DEFINED,
  construction_material USER-DEFINED,
  insulation_type USER-DEFINED,
  hvac_system_present boolean DEFAULT false,
  hvac_system_type USER-DEFINED,
  irrigation_system_type USER-DEFINED,
  lighting_system USER-DEFINED,
  length numeric,
  width numeric,
  height numeric,
  min_efficacious_gasifier_density_sqft_per_bag numeric DEFAULT 2000,
  recommended_placement_density_bags integer,
  has_dead_zones boolean DEFAULT false,
  num_regularly_opened_ports integer,
  state text,
  country text,
  timezone text,
  interior_working_surface_types ARRAY,
  microbial_risk_zone USER-DEFINED DEFAULT 'Medium'::microbial_risk_zone_enum,
  quantity_deadzones integer CHECK (quantity_deadzones IS NULL OR quantity_deadzones >= 1 AND quantity_deadzones <= 25),
  ventilation_strategy USER-DEFINED,
  site_code bigint,
  Number of Fans integer CHECK ("Number of Fans" < 51),
  airflow_vectors jsonb DEFAULT '[]'::jsonb,
  door_details jsonb DEFAULT '[]'::jsonb,
  number_of_platforms smallint DEFAULT '0'::smallint,
  platform_details jsonb DEFAULT '[]'::jsonb,
  company_id uuid,
  fan_details jsonb,
  wall_details jsonb DEFAULT '[{"wall_id": "north_wall", "material": "Polycarbonate", "end_point": {"x": 110, "y": 0}, "length_ft": 110, "orientation": "North", "start_point": {"x": 0, "y": 0}, "justification": "outside"}, {"wall_id": "east_wall", "material": "Polycarbonate", "end_point": {"x": 110, "y": 100}, "length_ft": 100, "orientation": "East", "start_point": {"x": 110, "y": 0}, "justification": "outside"}, {"wall_id": "south_wall", "material": "Polycarbonate", "end_point": {"x": 0, "y": 100}, "length_ft": 110, "orientation": "South", "start_point": {"x": 110, "y": 100}, "justification": "outside"}, {"wall_id": "west_wall", "material": "Polycarbonate", "end_point": {"x": 0, "y": 0}, "length_ft": 100, "orientation": "West", "start_point": {"x": 0, "y": 100}, "justification": "outside"}]'::jsonb,
  latitude numeric CHECK (latitude >= '-90'::integer::numeric AND latitude <= 90::numeric),
  longitude numeric CHECK (longitude >= '-180'::integer::numeric AND longitude <= 180::numeric),
  elevation_ft numeric,
  climate_zone character varying,
  facility_dimensions jsonb,
  facility_layout jsonb,
  CONSTRAINT sites_pkey PRIMARY KEY (site_id),
  CONSTRAINT sites_lastupdated_by_fkey FOREIGN KEY (lastupdated_by) REFERENCES auth.users(id),
  CONSTRAINT sites_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id)
);
CREATE TABLE public.split_petri_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  original_image_url text NOT NULL,
  main_petri_observation_id uuid NOT NULL,
  archived_at timestamp with time zone DEFAULT now(),
  processed_by_user_id uuid,
  CONSTRAINT split_petri_images_pkey PRIMARY KEY (id),
  CONSTRAINT split_petri_images_processed_by_user_id_fkey FOREIGN KEY (processed_by_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.submission_sessions (
  session_id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL UNIQUE,
  site_id uuid NOT NULL,
  program_id uuid NOT NULL,
  opened_by_user_id uuid,
  session_start_time timestamp with time zone NOT NULL DEFAULT now(),
  last_activity_time timestamp with time zone NOT NULL DEFAULT now(),
  session_status USER-DEFINED NOT NULL DEFAULT 'Opened'::session_status_enum,
  completion_time timestamp with time zone,
  completed_by_user_id uuid,
  percentage_complete numeric NOT NULL DEFAULT 0.00,
  valid_petris_logged integer NOT NULL DEFAULT 0,
  valid_gasifiers_logged integer NOT NULL DEFAULT 0,
  escalated_to_user_ids ARRAY,
  CONSTRAINT submission_sessions_pkey PRIMARY KEY (session_id),
  CONSTRAINT submission_sessions_completed_by_user_id_fkey FOREIGN KEY (completed_by_user_id) REFERENCES auth.users(id),
  CONSTRAINT submission_sessions_opened_by_user_id_fkey FOREIGN KEY (opened_by_user_id) REFERENCES auth.users(id),
  CONSTRAINT submission_sessions_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(submission_id)
);
CREATE TABLE public.submissions (
  submission_id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_id uuid NOT NULL,
  program_id uuid NOT NULL,
  temperature numeric NOT NULL,
  humidity numeric NOT NULL DEFAULT NULL::numeric,
  airflow USER-DEFINED NOT NULL,
  odor_distance USER-DEFINED NOT NULL,
  weather USER-DEFINED NOT NULL,
  notes character varying,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  program_name text,
  lastupdated_by uuid,
  indoor_temperature numeric CHECK (indoor_temperature >= 32::numeric AND indoor_temperature <= 120::numeric),
  indoor_humidity numeric CHECK (indoor_humidity >= 1::numeric AND indoor_humidity <= 100::numeric),
  global_submission_id bigint NOT NULL UNIQUE,
  submission_timezone text,
  session_status USER-DEFINED,
  company_id uuid NOT NULL,
  CONSTRAINT submissions_pkey PRIMARY KEY (submission_id),
  CONSTRAINT submissions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT submissions_lastupdated_by_fkey FOREIGN KEY (lastupdated_by) REFERENCES auth.users(id),
  CONSTRAINT submissions_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.sites(site_id),
  CONSTRAINT submissions_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.pilot_programs(program_id),
  CONSTRAINT submissions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(company_id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text,
  company text,
  avatar_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  company_id uuid,
  is_company_admin boolean DEFAULT false,
  is_super_admin boolean DEFAULT false,
  is_active boolean DEFAULT true,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);